sudo : required #terminal differences 
services :# provding service
  - docker
  
before install : #installing 
  - docker build  -t dev01/docker-react -f Docker.dev #command for building image 
script : #script for running
  - docker run -e CI=true dev01/docker-react npm run test
