sudo : required
services :
  - docker
  
before install :
  - docker build  -t dev01/docker-react -f Docker.dev #command for building 
script :
  - docker run -e CI=true dev01/docker-react npm run test
