sudo : required # sudo is a program
services : # provding service
  - docker # it is a software framework for building, running, and managing container.
  
before install : # this command run before installing docker
  - docker build  -t dev01/docker-react -f Docker.dev # command for building image 
script : # python script for running
  - docker run -e CI=true dev01/docker-react npm run test # testing 

