# .travis.yml is a short guide to using Travis CI with your cloud platform-hosted code repository
sudo : required # sudo is a program for Unix-like computer operating systems that 
                # enables users to run programs with the security privileges of another user,
services : # provding service
  - docker # software for builing and running containers
  
before install : #this command run before installing docker
  - docker build  -t dev01/docker-react -f Docker.dev # command for building image 
script : #python script for running
  - docker run -e CI=true dev01/docker-react npm run test # testing 

