version: '3' # specify versions
services:
  web:
    build:# build docker image 
      context: .
      dockerfile: Dockerfile.dev #buidling docker file
    ports:#specify ports
      - "3000:3000"
    volumes: # persistent storage location that exists outside of the container
      - /app/node_modules
      - .:/app   
  tests: # testing start
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes: # persistent storage location that exists outside of the container
      - /app/node_modules
      - .:/app
    command: ["npm", "run", "test"] #command for running 


    # we also have to provide network

