# yml is a config file for Docker Compose.It allows to deploy, combine, and configure multiple docker containers at the same time.


version: '3' # specify versions
services: # services that app uses
  web:
    build: # build docker image 
      context: . # . represents  location from we have to copy or where we have to paste in docker file 
      dockerfile: Dockerfile.dev #build dockerfile (dockerfile.dev is same file as we create yml file)

  #envirnoment variables
    #ENV
    ports:
      - "3000:3000" #or any other port just specify ports
    volumes: # persistent storage location that exists outside of the container
      - /app/node_modules # packages
      - .:/app   # working directory 
  tests: # testing start
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes: # persistent storage location that exists outside of the container
      - /app/node_modules
      - .:/app
    command: ["npm", "run", "test"] #command for running 


    # we also have to provide network like 
    # networks :

