version: '3' # specify versions
services: # services that app uses
  web:
    build: # build docker image 
      context: .
      dockerfile: Dockerfile.dev #build dockerfile (dockerfile.dev is same file as we create yml file)

  #envirnoment v
    ports:
      - "3000:3000" #or any other port just specify ports
    volumes: # persistent storage location that exists outside of the container
      - /app/node_modules # packages
      - .:/app   # working directory 
  tests: # testing start
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes: # persistent storage location that exists outside of the container
      - /app/node_modules
      - .:/app
    command: ["npm", "run", "test"] #command for running 


    # we also have to provide network like 
    # networks :

