version: '3'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev #buidling docker file
    ports:
      - "3000:3000"
    volumes: # persistent storage location that exists outside of the container
      - /app/node_modules
      - .:/app   
  tests:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - /app/node_modules
      - .:/app
    command: ["npm", "run", "test"]


    # we also have to porvide network

