# This Dockerfile uses the Node.js 16 Alpine image as its base.
FROM node:16-alpine 

WORKDIR /app #working directory  

COPY package.json . #copy package.json file from local to docker 

#for installing 
RUN npm install 

COPY . . #copy all files from locol to docker 
# we give here envirnoment variables 
 #environment:
     # OPENAI_API_KEY: ${OPENAI_API_KEY}
CMD [ "npm","run","start"] #Command for running 

# volumes :
