
FROM node:16-alpine #library

WORKDIR /app #working dirrcetory 

COPY package.json . #copy package.json file from local to docker 

RUN npm install #for installing 

COPY . . #copy all files from locol to docker 

CMD [ "npm","run","start"] #for running 
